import os
from dotenv import load_dotenv

basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, '.env'))

# Do not edit this file. Instead, create a a file named .env and set these variables there
class Config(object):
    CLIP_SECS = float(os.environ.get('CLIP_SECS') or 4)

    # Database
    DB_HOST = os.environ.get('DB_HOST')
    DB_NAME = os.environ.get('DB_NAME')
    DB_USER = os.environ.get('DB_USER')
    DB_PASSWORD = os.environ.get('DB_PASSWORD')

    # Azure Data Lake
    ADLS_ACCOUNT = os.environ.get('ADLS_ACCOUNT')
    ADLS_TENANT = os.environ.get('ADLS_TENANT')
    ADLS_CLIENT_ID = os.environ.get('ADLS_CLIENT_ID')
    ADLS_CLIENT_SECRET = os.environ.get('ADLS_CLIENT_SECRET')

